### ISSUE TITLE
Lower Experience Modifier

### ISSUE THREAD

**Issue by jaywheelerbennett** [sean-niemann/RSC-Single-Player#3]
Hi - This is amazing, love preserving this game. But I find 8x experience gain to be a little high. Is there a way to change that? Thanks!

**Comment by v317** [comment]
src/org/nemotech/rsc
- Open constants.java

- Change `    public static int EXPERIENCE_MULTIPLIER = 8;` to whatever you like.

- Compile and enjoy.

**Comment by jaywheelerbennett** [comment]
Great thank you!
